config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#              ratings_home GET    /ratings/home(.:format)                                                                  ratings#home
#                lists_home GET    /lists/home(.:format)                                                                    lists#home
#                      root GET    /                                                                                        users#index
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                     login GET    /login(.:format)                                                                         session#new
#                           POST   /login(.:format)                                                                         session#create
#                           DELETE /login(.:format)                                                                         session#destroy
#                 directors GET    /directors(.:format)                                                                     directors#index
#                           POST   /directors(.:format)                                                                     directors#create
#              new_director GET    /directors/new(.:format)                                                                 directors#new
#             edit_director GET    /directors/:id/edit(.:format)                                                            directors#edit
#                  director GET    /directors/:id(.:format)                                                                 directors#show
#                           PATCH  /directors/:id(.:format)                                                                 directors#update
#                           PUT    /directors/:id(.:format)                                                                 directors#update
#                           DELETE /directors/:id(.:format)                                                                 directors#destroy
#                     films GET    /films(.:format)                                                                         films#index
#                           POST   /films(.:format)                                                                         films#create
#                  new_film GET    /films/new(.:format)                                                                     films#new
#                 edit_film GET    /films/:id/edit(.:format)                                                                films#edit
#                      film GET    /films/:id(.:format)                                                                     films#show
#                           PATCH  /films/:id(.:format)                                                                     films#update
#                           PUT    /films/:id(.:format)                                                                     films#update
#                           DELETE /films/:id(.:format)                                                                     films#destroy
#                   ratings GET    /ratings(.:format)                                                                       ratings#index
#                           POST   /ratings(.:format)                                                                       ratings#create
#                new_rating GET    /ratings/new(.:format)                                                                   ratings#new
#               edit_rating GET    /ratings/:id/edit(.:format)                                                              ratings#edit
#                    rating GET    /ratings/:id(.:format)                                                                   ratings#show
#                           PATCH  /ratings/:id(.:format)                                                                   ratings#update
#                           PUT    /ratings/:id(.:format)                                                                   ratings#update
#                           DELETE /ratings/:id(.:format)                                                                   ratings#destroy
#                    search GET    /search(.:format)                                                                        films#search_form
#            search_results GET    /search/results(.:format)                                                                films#search_results
#                           GET    /movies/:id(.:format)                                                                    films#show_search
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do

  root :to => 'session#new'
  resources :users, :only => [:new, :create, :index]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :directors
  resources :films do
  resources :ratings
  end
  get "/search" => "films#search_form"

  get "/search/results" => "films#search_results"
  get "/movies/:id" => "films#show_search"

  
end

app/models/film.rb
# == Schema Information
#
# Table name: films
#
#  id           :bigint(8)        not null, primary key
#  title        :text
#  director     :text
#  release_date :date
#  genre        :text
#  country      :text
#  runtime      :integer
#  image        :text
#  plot         :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  director_id  :integer
#  rating       :float
#

class Film < ApplicationRecord
  belongs_to :director, :optional => true
  has_many :ratings
  has_and_belongs_to_many :genres
  has_and_belongs_to_many :lists

end

app/controllers/films_controller.rb
#require 'httparty'

class FilmsController < ApplicationController
  before_action :check_for_admin, :only => [:edit, :update]

  #include HTTParty

  # API_KEY = "24d863d54c86392e6e1df55b9a328755"
  $API_KEY = "24d863d54c86392e6e1df55b9a328755"
  $API_BASE_URL = "https://api.themoviedb.org/3"

  def search_form
    url = "#{$API_BASE_URL}/discover/movie?api_key=#{$API_KEY}&sort_by=popularity.desc"
    @info = HTTParty.get url
    url1 = "#{$API_BASE_URL}/discover/movie?api_key=#{$API_KEY}&primary_release_year=2010&sort_by=vote_average.desc"
    @bestmovie = HTTParty.get url1
    url2 = "#{$API_BASE_URL}/discover/movie?api_key=#{$API_KEY}&with_genres=18&primary_release_year=2018"
    @bestdrama = HTTParty.get url2
    url3 = "#{$API_BASE_URL}/discover/movie?api_key=#{$API_KEY}&certification_country=US&certification.lte=G&sort_by=popularity.desc"
    @bestkidsmovie = HTTParty.get url3
  end

  def search_results
   @query = params[:query]
   url = "#{$API_BASE_URL}/search/movie?api_key=#{$API_KEY}&query=#{@query}"
   response = HTTParty.get(url)
   @results = response['results']
  end

   def show_search
     url = "#{$API_BASE_URL}/movie/#{params[:id]}?api_key=#{$API_KEY}"
     @movie = HTTParty.get(url)
     # @film = Film.create :title => @movie['original_title'], :image => "https://image.tmdb.org/t/p/w500/#{@movie['poster_path']}", :release_date => @movie["release_date"], :rating => @movie["vote_average"], :plot => @movie["overview"]

     @film=Film.find_or_create_by(title:  @movie['original_title']) do |film|
       film.image = "https://image.tmdb.org/t/p/w500/#{@movie['poster_path']}"
       film.release_date = @movie["release_date"]
       film.rating = @movie["vote_average"]
       film.plot = @movie["overview"]
     end
     redirect_to @film
   end

   # def show_discover
   #   url = "#{API_BASE_URL}/discover/movie?api_key=#{API_KEY}&sort_by=popularity.desc"
   #   @info = HTTParty.get url
   #   url1 = "#{API_BASE_URL}/discover/movie?api_key=#{API_KEY}&primary_release_year=2010&sort_by=vote_average.desc"
   #   @bestmovie = HTTParty.get url1
   #   url2 = "#{API_BASE_URL}/discover/movie?api_key=#{API_KEY}&with_genres=18&primary_release_year=2018"
   #   @bestdrama = HTTParty.get url2
   #   url3 = "#{API_BASE_URL}/discover/movie?api_key=#{API_KEY}&certification_country=US&certification.lte=G&sort_by=popularity.desc"
   #   @bestkidsmovie = HTTParty.get url3
   # end



  def index
    @films = Film.all
    @genres = Genre.all
  end

  def show
    @film = Film.find params[:id]
    # @rating = Rating.create({review:params[:review], stars:params[:stars]})
    # raise 'hell'
  end

  def new
    @film = Film.new
  end

  def create
    film =Film.create film_params
    redirect_to film
  end

  def edit
    @film = Film.find params[:id]
  end

  def update
    film = Film.find params[:id]
    film.update film_params
    redirect_to film
  end

  def destroy
    film = Film.find params[:id]
    film.destroy
    redirect_to films_path
  end

  private
  def film_params
    params.require(:film).permit(:title, :genre, :country, :image, :director_id, :release_date, :director, :runtime, :plot)
  end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.erb
<%= form_for @film do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :autofocus => true %>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <%= f.label :release_date, "Release date" %>
  <%= f.text_field :release_date %>
  <%= f.label :Runtime %>
  <%= f.number_field :runtime %>
  <%= f.label :image %>
  <%= f.url_field :image, :required => true %>
  <%= f.label :director_id %>
  <%= f.select :director_id, Director.pluck(:name, :id), :include_blank => true %>
  <%= f.label :Description %>
  <%= f.text_field :plot%>
  <%= f.submit %>
<% end %>

app/views/films/edit.html.erb
<h2>Edit Film</h2>
<%= render :partial => 'form' %>

app/views/films/index.html.erb
<h2>All films</h2>
<% @films.each do |film| %>
  <% @genres.each do |genre| %>

      <% if film.genre == genre.name  %>
        <p><%= genre.name %></p>
        <p><%= link_to film.title, film %></p>
            <% if film.image.present? %>
              <%= link_to image_tag(film.image, :class => 'thumb'), film %>
            <% end %>
      <% end %>
  <% end %>
<% end %>

app/views/films/new.html.erb
<h2>New Film</h2>
<%= render :partial => 'form' %>

app/views/films/search_form.html.erb
<div class= "invite">
  <h1>Welcome to amazing MovieWorld</h1>
</div>
<div class="row">

<div class="col-10">
  <div class="box">
  <h1>The most popular movies</h1>
  </div>
  <div class="row">
    <% @info["results"].each do |movie| %>
      <div class="col">
        <p class="label"><%= movie["title"] %></p>
        <a href="/movies/<%= movie['id'] %>">
          <img class="image_size" src=<%= "https://image.tmdb.org/t/p/w200/#{movie["backdrop_path"]}" %> >
        </a>
      </div>
    <% end %>
  </div>
  <div class="box">
  <h1>The best movies from 2010</h1>
  </div>
  <div class="row">
    <% @bestmovie["results"].each do |movie| %>
      <div class="col">
        <% if movie["backdrop_path"].present? %>
          <p class="label"><%= movie["title"] %></p>
          <a href="/movies/<%= movie['id'] %>">
            <img class="image_size" src=<%= "https://image.tmdb.org/t/p/w200/#{movie["backdrop_path"]}" %> >
          </a>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="box">
  <h1>The best drama released in 2018</h1>
  </div>
  <div class="row">
    <% @bestdrama["results"].each do |movie| %>
      <div class="col">
        <% if movie["backdrop_path"].present? %>
          <p class="label"><%= movie["title"] %></p>
          <a href="/movies/<%= movie['id'] %>">
            <img class="image_size" src=<%= "https://image.tmdb.org/t/p/w200/#{movie["backdrop_path"]}" %> >
          </a>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="box">
  <h2>The most popular kids movies</h2>
  </div>
  <div class="row">
    <% @bestkidsmovie["results"].each do |movie| %>
      <div class="col">
        <% if movie["backdrop_path"].present? %>
          <p class="label"><%= movie["title"] %></p>
          <a href="/movies/<%= movie['id'] %>">
            <img class="image_size" src=<%= "https://image.tmdb.org/t/p/w200/#{movie["backdrop_path"]}" %> >
          </a>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<div class="col-2">
  <h4>Movie Search: </h4>

  <form action="/search/results" class="form-signin">

   Search Text: <input type="text" name="query" class="form-control">
   <input type="submit" value="search" class="btn btn-primary">
  </form>
</div>
</div>

app/views/films/search_results.html.erb
<h2>Search results for "<%= @query %>"</h2>

<ul>

<% @results.each do |movie| %>
 <li>
   <%= image_tag ("https://image.tmdb.org/t/p/w500/#{movie['poster_path']}"), :class => "icon" %>
   <a href="/movies/<%= movie['id'] %>">
     <%= movie['title'] %>
   </a>
 </li>
<% end %>
</ul>

app/views/films/show.html.erb
<div class="box">
  <h2><%= @film.title %></h2>
</div>
<div class="row">
  <div class="col">
    <% if @film.image.present? %>
    <%= image_tag @film.image, :alt => @film.title, :class => 'feature' %>
    <% end %>
  </div>
  <div class="col">
    <ul>
       <li><strong>Title: </strong> <%= @film.title %></li>
      <% if @film.director.present? %>
         <li>Director: <%= link_to @film.director.name, @film.director %></li>
      <% end %>
        <li><strong>Rating: </strong><%= @film.rating %></li>
        <li><strong>Release date: </strong><%= @film.release_date %></li>
        <li><strong>Description: </strong>Description: <%= @film.plot %></li>
    </ul>
  </div>
</div>



<div class="controls">
  <%= link_to "Watched movie", new_film_rating_path(@film.id), :class=>"btn btn-primary" %>
  <%# <%= button_to "Want to watch", new_film_path %>
  <% if @current_user.admin? %>
  <!-- <div class="controls"> -->
    <%= link_to 'Edit film', edit_film_path(@film), :class=>"btn btn-primary" %>
    <%= link_to 'Delete film', @film, :method => 'delete', :class=>"btn btn-primary" %>
  <% end %>
</div>

<h2>User Reviews:</h2>
<div>
  <% @film.ratings.each do |rating| %>
      <p><strong>Written by: </strong><%= rating.user.name %> </p>
      <div class="card">
        <div class="card-body">
          <p><%= simple_format(rating.review) %></p>
        </div>
      </div>

  <%  end %>
</div>

app/views/films/show_discover.html.erb
<!-- {"vote_count"=>861,
    "id"=>424783,
    "video"=>false,
    "vote_average"=>6.5,
    "title"=>"Bumblebee",
    "popularity"=>477.898,
    "poster_path"=>"/fw02ONlDhrYjTSZV8XO6hhU3ds3.jpg",
    "original_language"=>"en",
    "original_title"=>"Bumblebee",
    "genre_ids"=>[28, 12, 878],
    "backdrop_path"=>"/hMANgfPHR1tRObNp2oPiOi9mMlz.jpg",
    "adult"=>false,
    "overview"=>
     "On the run in the year 1987, Bumblebee finds refuge in a junkyard in a small Californian beach town. Charlie, on the cusp of turning 18 and trying to find her place in the world, discovers Bumblebee, battle-scarred and broken.  When Charlie revives him, she quickly learns this is no ordinary yellow VW bug.",
    "release_date"=>"2018-12-15"} -->
<h2>The most popular movies</h2>
<div class="row">
  <% @info["results"].each do |movie| %>
    <div class="col">
      <p><%= movie["title"] %></p>
      <a href="/movies/<%= movie['id'] %>">
        <img class="image_size" src=<%= "https://image.tmdb.org/t/p/w500/#{movie["backdrop_path"]}" %> >
      </a>
    </div>
  <% end %>
</div>

<h2>The best movies from 2010</h2>
<div class="row">
  <% @bestmovie["results"].each do |movie| %>
    <div class="col">
      <% if movie["backdrop_path"].present? %>
        <p><%= movie["title"] %></p>
        <a href="/movies/<%= movie['id'] %>">
          <img class="image_size" src=<%= "https://image.tmdb.org/t/p/w500/#{movie["backdrop_path"]}" %> >
        </a>
      <% end %>
    </div>
  <% end %>
</div>

<h2>The best drama released in 2018</h2>
<div class="row">
  <% @bestdrama["results"].each do |movie| %>
    <div class="col">
      <% if movie["backdrop_path"].present? %>
        <p><%= movie["title"] %></p>
        <a href="/movies/<%= movie['id'] %>">
          <img class="image_size" src=<%= "https://image.tmdb.org/t/p/w500/#{movie["backdrop_path"]}" %> >
        </a>
      <% end %>
    </div>
  <% end %>
</div>

<h2>The most popular kids movies</h2>
<div class="row">
  <% @bestkidsmovie["results"].each do |movie| %>
    <div class="col">
      <% if movie["backdrop_path"].present? %>
        <p><%= movie["title"] %></p>
        <a href="/movies/<%= movie['id'] %>">
          <img class="image_size" src=<%= "https://image.tmdb.org/t/p/w500/#{movie["backdrop_path"]}" %> >
        </a>
      <% end %>
    </div>
  <% end %>
</div>

app/views/films/show_search.html.erb
<h2><%= @movie['original_title'] %></h2>
<div class="row">
  <div class="col">
    <h2><%= image_tag ("https://image.tmdb.org/t/p/w500/#{@movie['poster_path']}") %></h2>
  </div>
  <div class="col">
    <p>
      <strong>Description:</strong>
     <%= @movie['overview'] %>
    </p>

    <p>
      <strong>Release date:</strong> <%= @movie['release_date'] %>
    </p>

    <p>
      <strong>Rating:</strong> <%= @movie['vote_average'] %>
    </p>
    <p>
      <strong>Revenue:</strong> $<%= @movie['revenue'] %>
    </p>
  </div>
</div>




<%= button_to "Watched movie", new_film_path %>
<%= button_to "Want to watch", new_film_path %>